[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.132.0"
image = "0.25.1"
find_folder = "0.3.0"
rand = "0.8.5"
rayon = "1.7.0"
smallvec = "1.13.2"